name: Mod SDcard

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      bootloader:
        description: "Select Bootloader"
        required: true
        default: "b860h"
        type: choice
        options:
          - b860h
          - hg680p
      fw_link:
        description: "Insert Firmware Link"
        required: true
        default: ""

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - name: SetUp environment
      run: |
        PWD=$(pwd)
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -y install wget python3
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo pip3 install gdown
        sudo pip3 install git+https://github.com/Juvenal-Yescas/mediafire-dl
        wget https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megacmd-xUbuntu_24.04_amd64.deb && sudo apt install "$PWD/megacmd-xUbuntu_24.04_amd64.deb"
        sudo mkdir -p openwrt

    - name: Download Firmware
      run: |
        if [ $(echo ${{ github.event.inputs.fw_link }} | grep "drive.") ]; then
          if [ $(echo ${{ github.event.inputs.fw_link }} | awk -F "/" '{print $6}') ]; then
            link_gdrive=$(echo ${{ github.event.inputs.fw_link }} | awk -F "/" '{print $6}')
          else
            link_gdrive=$(echo ${{ github.event.inputs.fw_link }} | awk -F "/" '{print $4}' | awk -F "?id=" '{print $2}'|awk -F "&export" '{print $1}')
          fi
          sudo gdown ${link_gdrive} -O openwrt/$(echo "${{ github.event.inputs.fw_link }}" | awk -F/ '{print $NF}') >/dev/null
        else
          if [ $(echo ${{ github.event.inputs.fw_link }} | grep "mediafire.com") ]; then
            sudo mediafire-dl ${{ github.event.inputs.fw_link }} -o openwrt/$(echo "${{ github.event.inputs.fw_link }}" | awk -F/ '{print $NF}') >/dev/null
          else
            if [ $(echo ${{ github.event.inputs.fw_link }} | grep "mega.nz") ]; then
              file_mega=$(sudo mega-get ${{ github.event.inputs.fw_link }} | awk -F: '{print $2}')
              sudo mv ${file_mega} openwrt/$(echo "${{ github.event.inputs.fw_link }}" | awk -F/ '{print $NF}')
            else
              sudo wget --no-check-certificate ${{ github.event.inputs.fw_link }} -O openwrt/$(echo "${{ github.event.inputs.fw_link }}" | awk -F/ '{print $NF}') >/dev/null
            fi
          fi
        fi

    - name: Get extension
      id: get_extension
      run: |
        filename=$(find ./openwrt -name "*.img.*")
        extension=$(basename "$filename" | sed -E 's/.*\.(img\.(gz|xz))$/\1/')
        no_extension=$(basename "$filename" | sed -E 's/\.(gz|xz)$//')
        echo "file_type=$extension" >> $GITHUB_ENV
        echo "file_name=$no_extension" >> $GITHUB_ENV
        
    - name: Extract firmware
      run: |
        sudo mkdir -p openwrt/boot
        sudo mv BootCardMaker/u-boot.bin openwrt/
        sudo mv files/mod-boot-sdcard.tar.gz openwrt/
        cd openwrt
        if [ ${{ env.file_type }} = "img.gz" ]; then
          sudo gunzip ${{ env.file_name }}.gz
        else
          sudo unxz ${{ env.file_name }}.xz
        fi
        device=$(sudo losetup -fP --show ${{ env.file_name }})
        sudo mount ${device}p1 boot
        sudo tar -xzvf mod-boot-sdcard.tar.gz -C boot
        uenv=$(sudo cat boot/uEnv.txt | grep APPEND | awk -F "root=" '{print $2}')
        extlinux=$(sudo cat boot/extlinux/extlinux.conf | grep append | awk -F "root=" '{print $2}')
        sudo sed -i "s/$extlinux/$uenv/g" boot/extlinux/extlinux.conf
        sleep 1
        if [ ${{ github.event.inputs.bootloader }} = "b860h" ]; then
          dtb="meson-gxl-s905x-b860h.dtb"
        elif [ ${{ github.event.inputs.bootloader }} = "hg680p" ]; then
          dtb="meson-gxl-s905x-p212.dtb"
        fi
        boot=$(sudo cat boot/boot.ini | grep dtb | awk -F "/" '{print $4}' | cut -d'"' -f1)
        sudo sed -i "s/$boot/$dtb/g" boot/boot.ini
        sudo sed -i "s/$boot/$dtb/g" boot/extlinux/extlinux.conf
        sudo sed -i "s/$boot/$dtb/g" boot/uEnv.txt
        sudo umount ${device}p1
        sleep 1
        sudo dd if=u-boot.bin of=${device} bs=1 count=444 conv=fsync 2>/dev/null
        sudo dd if=u-boot.bin of=${device} bs=512 skip=1 seek=1 conv=fsync 2>/dev/null
        sudo losetup -d ${device}
        sleep 1
        if [ ${{ env.file_type }} = "img.gz" ]; then
          sudo gzip ${{ env.file_name }}
        else
          sudo xz ${{ env.file_name }}
        fi

    - name: Find Firmware
      run: |
        FILE_PATH=$(find -name "*.img.*")
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
        echo -e "FILE_PATH path: $FILE_PATH"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        name: houjie-Wrt_Mod_SDCard
        tag_name: All
        draft: false
        prerelease: false
        files: |
              ${{ env.FILE_PATH }}
        body: |
              Mod SDCard
